ARDUINO_DIR = /opt/arduino
BOARD_TAG = diecimila
BOARD_SUB = atmega328

ARDUINO_LIBS = Wire Grove_LCD_RGB_Backlight Grove_Temperature_And_Humidity_Sensor-master U8glib

include ~/.makefiles/Arduino-check-syntax.mk
